import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Otherbody from "@/components/Otherbody";
import { Inter } from "next/font/google";
import "../../node_modules/bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hoch poch app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <Header />
          {children}
          <Otherbody />
          <button className="btn btn-sm btn-info">Testing</button>
          <Footer />
        </div>
      </body>
    </html>
  );
}
